columnSuffix: null
contentColumnType: string
fieldGroup: 9927dfb8-a401-4f31-9999-2e1e6227028e # Common
handle: uberUns
instructions: null
name: 'Ãœber uns'
searchable: false
settings:
  contentTable: '{{%matrixcontent_uberuns}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
